namespace: scoreserver

resources:
  - ../base
  - params.yaml

components:
  - ../components

configMapGenerator:
  - name: scoreserver-backend-config
    behavior: merge
    files:
      - admin-auth-config.yaml

images:
  - name: backend
    newName: ghcr.io/ictsc/ictsc-regalia/backend
    newTag: sha-2dc9ea8
  - name: frontend
    newName: ghcr.io/ictsc/ictsc-regalia/frontend
    newTag: sha-2dc9ea8
  - name: batch
    newName: ghcr.io/ictsc/ictsc-regalia/batch
    newTag: sha-2dc9ea8
  - name: toolbox
    newName: ghcr.io/ictsc/ictsc-regalia/toolbox
    newTag: sha-2dc9ea8
  - name: discord-admin-bot
    newName: ghcr.io/ictsc/ictsc-discord-bot
    newTag: sha-d9e14d2
