apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scoreserver-batch
  labels:
    app.kubernetes.io/name: scoreserver-batch
    app.kubernetes.io/component: batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-batch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-batch
    spec:
      serviceAccountName: scoreserver-batch
      volumes:
        - name: admin-api-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: contest.ictsc.net
                  path: token
              - secret:
                  name: sstate-secrets
                  items:
                    - key: sstate-ca.crt
                      path: sstate-ca.crt
        - name: otel-col-config
          configMap:
            name: otel-col-config
      initContainers:
        - name: otelcol
          image: otel/opentelemetry-collector:0.121.0
          restartPolicy: Always
          args:
            - --config=/etc/otel-col-config.yaml
          volumeMounts:
            - name: otel-col-config
              mountPath: /etc/otel-col-config.yaml
              subPath: otel-col-config.yaml
          ports:
            - containerPort: 9090
              name: metrics
          resources:
            requests:
              memory: 8Mi
              cpu: 5m
            limits:
              memory: 32Mi
              cpu: 20m
      containers:
        - name: batch
          image: batch
          args:
            - --api-url=http://scoreserver-backend:8081
            - --api-token-file=/var/run/secrets/batch/token 
            - --sstate-tls-skip-verify
            - --sstate-ca-file=/var/run/secrets/batch/sstate-ca.crt
          env:
            - name: SSTATE_URL
              valueFrom:
                secretKeyRef:
                  name: sstate-secrets
                  key: url 
            - name: SSTATE_USER
              valueFrom:
                secretKeyRef:
                  name: sstate-secrets
                  key: user
            - name: SSTATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sstate-secrets
                  key: password
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4317
          volumeMounts:
            - name: admin-api-token
              mountPath: /var/run/secrets/batch
              readOnly: true
          resources:
            limits:
              memory: 128Mi
