server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    root /var/lib/git-sync/current/images;

    location = /healthz {
        access_log off;
        return 200;
    }

    location / {
        try_files $uri =404;
    }
}
