apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-maintenance
  labels:
    app.kubernetes.io/name: scoreserver-maintenance
    app.kubernetes.io/component: maintenance
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-maintenance
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-maintenance
        app.kubernetes.io/component: maintenance
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: maintenance-html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: 8Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 100m
      volumes:
        - name: maintenance-html
          configMap:
            name: scoreserver-maintenance-html
        - name: nginx-conf
          configMap:
            name: scoreserver-maintenance-nginx-conf

