apiVersion: v1
kind: Service
metadata:
  name: scoreserver-maintenance
  labels:
    app.kubernetes.io/name: scoreserver-maintenance
    app.kubernetes.io/component: maintenance
spec:
  selector:
    app.kubernetes.io/name: scoreserver-maintenance
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80