resources:
  - ../base
  - ingress-contestant.yaml
  - ingress-admin.yaml
  # - ./maintenance

namespace: scoreserver

images:
  - name: backend
    newName: ghcr.io/ictsc/ictsc-regalia/backend
    newTag: sha-e4cbff5
  - name: frontend
    newName: ghcr.io/ictsc/ictsc-regalia/frontend
    newTag: sha-e4cbff5
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.8.1

configMapGenerator:
  - name: backend-env
    literals:
      - contestant-base-url=https://contest.ictsc.net/api
  - name: backend-config
    files:
      - admin-auth-policy.csv
      - admin-auth-config.yaml
  - name: oauth2-proxy-env
    literals:
      - client-id=dex-scoreserver-client
      - oidc-issuer-url=https://dex.drove.ictsc.net
      - redirect-url=https://contest-admin.ictsc.net/oauth2/callback
