namespace: scoreserver

resources:
  - ../base
  - params.yaml

components:
  - ../components

patches:
  - path: contestant-httproute-patch.yaml

configMapGenerator:
  - name: scoreserver-backend-config
    behavior: merge
    files:
      - admin-auth-config.yaml

images:
  - name: backend
    newName: ghcr.io/ictsc/ictsc-regalia/backend
    newTag: sha-bff0a99
  - name: frontend
    newName: ghcr.io/ictsc/ictsc-regalia/frontend
    newTag: sha-bff0a99
  - name: batch
    newName: ghcr.io/ictsc/ictsc-regalia/batch
    newTag: sha-bff0a99
  - name: toolbox
    newName: ghcr.io/ictsc/ictsc-regalia/toolbox
    newTag: sha-bff0a99
  - name: discord-admin-bot
    newName: ghcr.io/ictsc/ictsc-discord-bot
    newTag: sha-d9e14d2
  - name: nginx
    newName: nginx
    newTag: 1.27.4
  - name: git-sync
    newName: registry.k8s.io/git-sync/git-sync
    newTag: v4.6.0
