namespace: scoreserver

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - scoreserver.env
    name: scoreserver-secrets
  - envs:
      - oauth2-proxy.env
    name: oauth2-proxy-secret

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: secret-management-gha
