namespace: scoreserver

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - scoreserver.env
    name: scoreserver-secrets
  - envs:
      - oauth2-proxy.env
    name: oauth2-proxy-secret
  - envs:
      - discord-admin-bot.env
    name: discord-admin-bot-secrets

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: secret-management-gha
