apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scoreserver-batch
  labels:
    app.kubernetes.io/name: scoreserver-batch
    app.kubernetes.io/component: batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-batch
      app.kubernetes.io/component: batch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-batch
        app.kubernetes.io/component: batch
    spec:
      serviceAccountName: scoreserver-batch
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: batch
          image: batch
          args:
            - --api-url=http://scoreserver-backend:8081
            - --api-token-file=/run/ictstore-secrets/token
            - --sstate-ca-file=/run/sstate-ca/ca.crt
          env:
            - name: SSTATE_URL
              value: https://sstate.ictsc.net
            - name: SSTATE_USER
              value: ictsc
            - name: SSTATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scoreserver-sstate-credentials
                  key: password
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "15000"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otlp.telemetry:4317
            - name: OTEL_TRACES_EXPORTER
              value: none
          volumeMounts:
            - mountPath: /run/ictstore-secrets
              name: ictscore-secrets
              readOnly: true
            - mountPath: /run/sstate-credentials
              name: sstate-credentials
              readOnly: true
            - mountPath: /run/sstate-ca
              name: sstate-ca
              readOnly: true
          resources:
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: ictscore-secrets
          projected:
            sources:
              - serviceAccountToken:
                  audience: contest.ictsc.net
                  path: token
        - name: sstate-credentials
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: scoreserver-sstate-credentials
        - name: sstate-ca
          configMap:
            name: scoreserver-sstate-ca
