apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreserver-backend
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: scoreserver-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scoreserver-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scoreserver-backend
    spec:
      initContainers:
        - name: otelcol
          image: otel/opentelemetry-collector:0.121.0
          restartPolicy: Always
          args:
            - --config=/etc/otel-col-config.yaml
          volumeMounts:
            - name: otel-col-config
              mountPath: /etc/otel-col-config.yaml
              subPath: otel-col-config.yaml
          ports:
            - containerPort: 9090
              name: metrics
          resources:
            requests:
              memory: 8Mi
              cpu: 5m
            limits:
              memory: 32Mi
              cpu: 20m
      containers:
        - name: scoreserver
          image: backend
          args:
            - --contestant.http-addr=0.0.0.0:8080
            - --admin.http-addr=0.0.0.0:8081
            - --admin.auth-config-file=/etc/scoreserver/admin-auth-config.yaml
            - --admin.auth-policy-file=/etc/scoreserver/admin-auth-policy.csv
          env:
            - name: CONTESTANT_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: contestant-base-url
            - name: PGHOST
              value: ictsc-cluster
            - name: PGDATABASE
              value: ictscore
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ictsc.ictsc-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: REDIS_URL
              value: redis://redis-haproxy.scoreserver.svc.cluster.local:6379/0
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: scoreserver-secrets
                  key: discord-client-id
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: scoreserver-secrets
                  key: discord-client-secret
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4317
          ports:
            - containerPort: 8080
              name: contestant
            - containerPort: 8081
              name: admin
          volumeMounts:
            - name: config
              mountPath: /etc/scoreserver
              readOnly: true
          livenessProbe:
            initialDelaySeconds: 10
            grpc:
              port: 8081
          resources:
            requests:
              memory: 16Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: "1"
      volumes:
        - name: config
          configMap:
            name: backend-config
        - name: otel-col-config
          configMap:
            name: otel-col-config
