resources:
  - database.yaml
  - migrate.yaml
  - frontend.yaml
  - backend
  - images
  - batch.yaml
  - metrics-collector.yaml
  # - discord-admin-bot.yaml
  - httproute.yaml
  # - maintenance

configMapGenerator:
  - name: scoreserver-sstate-ca
    files:
      - ca.crt=sstate-ca.crt
  - name: scoreserver-metrics-collector-config
    files:
      - collector.yaml=metrics-collector-config.yaml
    options:
      labels:
        app.kubernetes.io/name: scoreserver-metrics-collector
        app.kubernetes.io/component: metrics-collector

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: scoreserver
