resources:
  - service.yaml
  - deploy-backend.yaml
  - deploy-frontend.yaml
  - deploy-oauth2-proxy.yaml
  - pod-monitor.yaml
  - middleware.yaml
  - maintenance
  - secret-manager-role.yaml
  - sstate-monitor-sa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: scoreserver

configMapGenerator:
  - name: otel-col-config
    files:
      - otel-col-config.yaml
