apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - scoreserver-secrets
      - oauth2-proxy-secret
      - discord-admin-bot-secrets
      - sstate-secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "detete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: github.com/ictsc/ictsc-regalia-release
