name: Apply Secrets
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - secret/**

jobs:
  apply:
    name: Apply secrets to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.39.1
      - name: Build manifest
        run: make -C secret
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          GROWI_API_TOKEN: ${{ secrets.GROWI_API_TOKEN }}
          OAUTH2_PROXY_COOKIE_SECRET: ${{ secrets.OAUTH2_PROXY_COOKIE_SECRET }}
          OAUTH2_PROXY_CLIENT_SECRET: ${{ secrets.OAUTH2_PROXY_CLIENT_SECRET }}
      - name: Set kubectl config
        run: |
          kubectl config set-cluster default \
            --embed-certs=true \
            --server="$K8S_SERVER" \
            --certificate-authority=<(echo "$K8S_CA")
          kubectl config set-credentials gha \
            --embed-certs=true \
            --client-certificate=<(echo "$K8S_CLIENT_CERT") \
            --client-key=<(echo "$K8S_CLIENT_KEY")
          kubectl config set-context default --cluster=default --user=gha
          kubectl config use-context default
        env:
          K8S_SERVER: ${{ vars.K8S_SERVER }}
          K8S_CA: ${{ vars.K8S_CA }}
          K8S_CLIENT_CERT: ${{ secrets.K8S_CLIENT_CERT }}
          K8S_CLIENT_KEY: ${{ secrets.K8S_CLIENT_KEY }}
      - name: Apply manifest
        run: kubectl apply -f secret/manifest.yaml
